name: Format

on:
  push:
    branches:
    - master
  pull_request:

jobs:

  solidity:
    runs-on: ubuntu-latest

    steps:
    - name: Check out github repository
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      with:
        fetch-depth: 1

    - name: Install Foundry
      uses: foundry-rs/foundry-toolchain@c7450ba673e133f5ee30098b3b54f444d3a2ca2d # v1
      with:
        version: nightly

    - name: Check Solidity formatting
      run: forge fmt --check
