name: Format

on:
  push:
    branches:
    - master
  pull_request:

jobs:

  solidity:
    runs-on: ubuntu-latest

    steps:
    - name: Check out github repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: Install Foundry
      uses: foundry-rs/foundry-toolchain@v1
      with:
        version: nightly

    - name: Check Solidity formatting
      run: forge fmt --check
